# Assignment 4 Real-time text classification in the browser
### Jing Qian (jq2282)

## Part 1

### Step 1. Environment Preparation

In [0]:
!pip install tensorflow==2.0.0-alpha0

In [0]:
!pip install tensorflowjs==1.0.1

Connet to the github page, use the applied-dl repository: https://github.com/fakeJQ/applied-dl. 

Generated page of the repository, shown as: https://fakejq.github.io/applied-dl/

### Step 2. Copy repository from Github

In [0]:
# your github username
USER_NAME = "fakeJQ" 

# the email associated with your commits
# (may not matter if you leave it as is)
USER_EMAIL = "tcqj_8758@163.com" 

# create a token by visiting https://github.com/settings/tokens
# choose public permissions
# important: treat this token like a password (do not commit it)
# or submit it w/ your HW.
TOKEN = "89d35eaae4bb746d07f304526f39807c2c267f5c" 

# for example, if your user_name is "foo", then this notebook will create
# a site at "https://foo.github.io/hw4/"
SITE_NAME = "hw4"

In [0]:
!git config --global user.email {USER_NAME}
!git config --global user.name  {USER_EMAIL}

In [0]:
import os
repo_path = USER_NAME + '.github.io'
if not os.path.exists(os.path.join(os.getcwd(), repo_path)):
  !git clone https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/applied-dl

fatal: destination path 'applied-dl' already exists and is not an empty directory.


In [0]:
os.chdir('/content/applied-dl')
!git pull

Already up to date.


In [0]:
project_path = os.path.join(os.getcwd(), SITE_NAME)
if not os.path.exists(project_path): 
  os.mkdir(project_path)
os.chdir(project_path)

In [0]:
print(project_path)

/content/applied-dl/hw4


### Step 3. Data preparation 

In [0]:
# DO NOT MODIFY
MODEL_DIR = os.path.join(project_path, "model_js")
if not os.path.exists(MODEL_DIR):
  os.mkdir(MODEL_DIR)

In [0]:
# A few sentences from Alice in Wonderland
ex1 = "Alice was beginning to get very tired of sitting by her sister on the bank."
ex2 = "Once or twice she had peeped into the book her sister was reading, but it had no pictures or conversations in it."

# Dracula
ex3 = "Buda-Pesth seems a wonderful place."
ex4 = "Left Munich at 8:35 P. M., on 1st May, arriving at Vienna early next morning."

# Illiad
ex5 = "Scepticism was as much the result of knowledge, as knowledge is of scepticism."
ex6 = "To be content with what we at present know, is, for the most part, to shut our ears against conviction."

In [0]:
x_train = [ex1, ex2, ex3, ex4, ex5, ex6]
y_train = [0, 0, 1, 1, 2, 2] # Indicating which book each sentence is from

In [0]:
max_len = 20
num_words = 1000
from keras.preprocessing.text import Tokenizer
# Fit the tokenizer on the training data
t = Tokenizer(num_words=num_words)
t.fit_on_texts(x_train)

Using TensorFlow backend.


In [0]:
print(t.word_index)

{'the': 1, 'was': 2, 'to': 3, 'of': 4, 'at': 5, 'her': 6, 'sister': 7, 'on': 8, 'or': 9, 'had': 10, 'it': 11, 'scepticism': 12, 'as': 13, 'knowledge': 14, 'is': 15, 'alice': 16, 'beginning': 17, 'get': 18, 'very': 19, 'tired': 20, 'sitting': 21, 'by': 22, 'bank': 23, 'once': 24, 'twice': 25, 'she': 26, 'peeped': 27, 'into': 28, 'book': 29, 'reading': 30, 'but': 31, 'no': 32, 'pictures': 33, 'conversations': 34, 'in': 35, 'buda': 36, 'pesth': 37, 'seems': 38, 'a': 39, 'wonderful': 40, 'place': 41, 'left': 42, 'munich': 43, '8': 44, '35': 45, 'p': 46, 'm': 47, '1st': 48, 'may': 49, 'arriving': 50, 'vienna': 51, 'early': 52, 'next': 53, 'morning': 54, 'much': 55, 'result': 56, 'be': 57, 'content': 58, 'with': 59, 'what': 60, 'we': 61, 'present': 62, 'know': 63, 'for': 64, 'most': 65, 'part': 66, 'shut': 67, 'our': 68, 'ears': 69, 'against': 70, 'conviction': 71}


In [0]:
vectorized = t.texts_to_sequences([ex1])
print(vectorized)

[[16, 2, 17, 3, 18, 19, 20, 4, 21, 22, 6, 7, 8, 1, 23]]


In [0]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded = pad_sequences(vectorized, maxlen=max_len, padding='post')

In [0]:
print(padded)

[[16  2 17  3 18 19 20  4 21 22  6  7  8  1 23  0  0  0  0  0]]


In [0]:

metadata = {
  'word_index': t.word_index,
  'max_len': max_len,
  'vocabulary_size': num_words,
}

### Step 4. Define a model, train and test

In [0]:

embedding_size = 8
n_classes = 3
epochs = 10
import tensorflow as tf

model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(num_words, embedding_size, input_shape=(max_len,)))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(3, activation='softmax'))
model.compile('adam', 'sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 8)             8000      
_________________________________________________________________
flatten (Flatten)            (None, 160)               0         
_________________________________________________________________
dense (Dense)                (None, 3)                 483       
Total params: 8,483
Trainable params: 8,483
Non-trainable params: 0
_________________________________________________________________


In [0]:

x_train = t.texts_to_sequences(x_train)
x_train = pad_sequences(x_train, maxlen=max_len, padding='post')
print(x_train)

[[16  2 17  3 18 19 20  4 21 22  6  7  8  1 23  0  0  0  0  0]
 [25 26 10 27 28  1 29  6  7  2 30 31 11 10 32 33  9 34 35 11]
 [36 37 38 39 40 41  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [42 43  5 44 45 46 47  8 48 49 50  5 51 52 53 54  0  0  0  0]
 [12  2 13 55  1 56  4 14 13 14 15  4 12  0  0  0  0  0  0  0]
 [ 3 57 58 59 60 61  5 62 63 15 64  1 65 66  3 67 68 69 70 71]]


In [0]:

model.fit(x_train, y_train, epochs=epochs)

Epoch 1/10
6/6 [==============================] - 0s 21ms/sample - loss: 1.0910 - accuracy: 0.1667
Epoch 2/10
6/6 [==============================] - 0s 725us/sample - loss: 1.0814 - accuracy: 0.3333
Epoch 3/10
6/6 [==============================] - 0s 416us/sample - loss: 1.0719 - accuracy: 0.6667
Epoch 4/10
6/6 [==============================] - 0s 386us/sample - loss: 1.0623 - accuracy: 1.0000
Epoch 5/10
6/6 [==============================] - 0s 381us/sample - loss: 1.0528 - accuracy: 1.0000
Epoch 6/10
6/6 [==============================] - 0s 460us/sample - loss: 1.0433 - accuracy: 1.0000
Epoch 7/10
6/6 [==============================] - 0s 414us/sample - loss: 1.0338 - accuracy: 1.0000
Epoch 8/10
6/6 [==============================] - 0s 412us/sample - loss: 1.0243 - accuracy: 1.0000
Epoch 9/10
6/6 [==============================] - 0s 599us/sample - loss: 1.0148 - accuracy: 1.0000
Epoch 10/10
6/6 [==============================] - 0s 313us/sample - loss: 1.0053 - accuracy: 1.0000


In [0]:
test_example = "Left Munich at 8:35 P. M., on 1st May, arriving at Vienna early next morning."
x_test = t.texts_to_sequences([test_example])
x_test = pad_sequences(x_test, maxlen=max_len, padding='post')
print(x_test)

[[42 43  5 44 45 46 47  8 48 49 50  5 51 52 53 54  0  0  0  0]]


In [0]:

preds = model.predict(x_test)
print(preds)
import numpy as np
print(np.argmax(preds))

[[0.30840474 0.3829351  0.30866015]]
1


### Step 5. Goto html!

In [0]:
import json
import tensorflowjs as tfjs


metadata_json_path = os.path.join(MODEL_DIR, 'metadata.json')
json.dump(metadata, open(metadata_json_path, 'wt'))
tfjs.converters.save_keras_model(model, MODEL_DIR)
print('\nSaved model artifcats in directory: %s' % MODEL_DIR)


Saved model artifcats in directory: /content/applied-dl/hw4/model_js


In [0]:
index_html = """
<!doctype html>

<body>
  <style>
    #textfield {
      font-size: 120%;
      width: 60%;
      height: 200px;
    }
  </style>
  <h1>
    Title
  </h1>
  <hr>
  <div class="create-model">
    <button id="load-model" style="display:none">Load model</button>
  </div>
  <div>
    <div>
      <span>Vocabulary size: </span>
      <span id="vocabularySize"></span>
    </div>
    <div>
      <span>Max length: </span>
      <span id="maxLen"></span>
    </div>
  </div>
  <hr>
  <div>
    <select id="example-select" class="form-control">
      <option value="example1">Alice's Adventures in Wonderland</option>
      <option value="example2">Dracula</option>
      <option value="example3">The Iliad</option>
    </select>
  </div>
  <div>
    <textarea id="text-entry"></textarea>
  </div>
  <hr>
  <div>
    <span id="status">Standing by.</span>
  </div>

  <script src='https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js'></script>
  <script src='index.js'></script>
</body>
"""

In [0]:
index_js = """
const HOSTED_URLS = {
  model:
      'model_js/model.json',
  metadata:
      'model_js/metadata.json'
};

const examples = {
  'example1':
      'Alice was beginning to get very tired of sitting by her sister on the bank.',
  'example2':
      'Buda-Pesth seems a wonderful place.',
  'example3':
      'Scepticism was as much the result of knowledge, as knowledge is of scepticism.'      
};

function status(statusText) {
  console.log(statusText);
  document.getElementById('status').textContent = statusText;
}

function showMetadata(metadataJSON) {
  document.getElementById('vocabularySize').textContent =
      metadataJSON['vocabulary_size'];
  document.getElementById('maxLen').textContent =
      metadataJSON['max_len'];
}

function settextField(text, predict) {
  const textField = document.getElementById('text-entry');
  textField.value = text;
  doPredict(predict);
}

function setPredictFunction(predict) {
  const textField = document.getElementById('text-entry');
  textField.addEventListener('input', () => doPredict(predict));
}

function disableLoadModelButtons() {
  document.getElementById('load-model').style.display = 'none';
}

function doPredict(predict) {
  const textField = document.getElementById('text-entry');
  const result = predict(textField.value);
  score_string = "Class scores: ";
  for (var x in result.score) {
    score_string += x + " ->  " + result.score[x].toFixed(3) + ", "
  }
  //console.log(score_string);
  status(
      score_string + ' elapsed: ' + result.elapsed.toFixed(3) + ' ms)');
}

function prepUI(predict) {
  setPredictFunction(predict);
  const testExampleSelect = document.getElementById('example-select');
  testExampleSelect.addEventListener('change', () => {
    settextField(examples[testExampleSelect.value], predict);
  });
  settextField(examples['example1'], predict);
}

async function urlExists(url) {
  status('Testing url ' + url);
  try {
    const response = await fetch(url, {method: 'HEAD'});
    return response.ok;
  } catch (err) {
    return false;
  }
}

async function loadHostedPretrainedModel(url) {
  status('Loading pretrained model from ' + url);
  try {
    const model = await tf.loadLayersModel(url);
    status('Done loading pretrained model.');
    disableLoadModelButtons();
    return model;
  } catch (err) {
    console.error(err);
    status('Loading pretrained model failed.');
  }
}

async function loadHostedMetadata(url) {
  status('Loading metadata from ' + url);
  try {
    const metadataJson = await fetch(url);
    const metadata = await metadataJson.json();
    status('Done loading metadata.');
    return metadata;
  } catch (err) {
    console.error(err);
    status('Loading metadata failed.');
  }
}

class Classifier {

  async init(urls) {
    this.urls = urls;
    this.model = await loadHostedPretrainedModel(urls.model);
    await this.loadMetadata();
    return this;
  }

  async loadMetadata() {
    const metadata =
        await loadHostedMetadata(this.urls.metadata);
    showMetadata(metadata);
    this.maxLen = metadata['max_len'];
    console.log('maxLen = ' + this.maxLen);
    this.wordIndex = metadata['word_index']
  }

  predict(text) {
    // Convert to lower case and remove all punctuations.
    const inputText =
        text.trim().toLowerCase().replace(/(\.|\,|\!)/g, '').split(' ');
    // Look up word indices.
    const inputBuffer = tf.buffer([1, this.maxLen], 'float32');
    for (let i = 0; i < inputText.length; ++i) {
      const word = inputText[i];
      inputBuffer.set(this.wordIndex[word], 0, i);
      //console.log(word, this.wordIndex[word], inputBuffer);
    }
    const input = inputBuffer.toTensor();
    //console.log(input);

    status('Running inference');
    const beginMs = performance.now();
    const predictOut = this.model.predict(input);
    //console.log(predictOut.dataSync());
    const score = predictOut.dataSync();//[0];
    predictOut.dispose();
    const endMs = performance.now();

    return {score: score, elapsed: (endMs - beginMs)};
  }
};

async function setup() {
  if (await urlExists(HOSTED_URLS.model)) {
    status('Model available: ' + HOSTED_URLS.model);
    const button = document.getElementById('load-model');
    button.addEventListener('click', async () => {
      const predictor = await new Classifier().init(HOSTED_URLS);
      prepUI(x => predictor.predict(x));
    });
    button.style.display = 'inline-block';
  }

  status('Standing by.');
}

setup();
"""

In [0]:
with open('index.html','w') as f:
  f.write(index_html)
  
with open('index.js','w') as f:
  f.write(index_js)

In [0]:
!ls

index.html  index.js  model_js


In [0]:
#!git add . 
#!git commit -m "colab -> github"
!git push https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/applied-dl.git master
#!git push https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/applied-dl

Counting objects: 9, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 34.15 KiB | 11.38 MiB/s, done.
Total 9 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/fakeJQ/applied-dl.git
   f116369..0804b74  master -> master


In [0]:
print("Now, visit https://%s.github.io/applied-dl/%s/" % (USER_NAME, SITE_NAME))

Now, visit https://fakeJQ.github.io/applied-dl/hw4/
